config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
get '/logout', to: 'sessions#destroy'

  

    resources :users
    resources :boats do
      resources :jobs
  end

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  validates :name, uniqueness: true, on: :create
  validates_inclusion_of :location, :in => %w( Halifax Havana Jakarta Los Angeles Split)
  # validates presence of array of locales [Jakarta, Havana, Split, Los Angeles, Halifax]
  belongs_to :user
  has_many :jobs, dependent: :destroy

  has_attached_file :avatar, :styles => { :thumb => "60x60>" }, :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :boats
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_confirmation_of :password 
	# validates_presence_of :password, on: :create
	validates :email, presence: true, uniqueness: true, on: :create
	# validates_presence_of :location
	has_many :boats, dependent: :destroy
	has_many :jobs, dependent: :destroy
	
	# has_many :boats, through:userfollowship
end


# UserFollowship.rb

# User 				Ships
# user1	(Bob)		ship1, ship3, ship4
# user2 (Moe)	    ship2

			# UserFolloship Joint Table

			# user_id	ship_id
			# 2			#3
			# Moe is following Bob's ship3

# the ships followed by a user would be written as
# user.userfollowship

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
  	@current_user||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
  	@boats = Boat.all
  end

  def show
  	@boat = Boat.find(params[:id])
    @jobs = Job.where(boat_id: params[:id])
  end

  def new
  	@boat = Boat.new
    @user = current_user
  end

  def create
    @boat = current_user.boats.build(boat_params)
    if @boat.save
      puts "?????????????????????????????????"
      redirect_to user_path(current_user)
    else
      p "?????????????????????????????????else render"
      flash[:alert] = "Whoops. Make sure all fields are filled."
      render new_boat_path
    end
  end
# 	  @boat = current_user.boats.build(boat_params)
# 	 	if @boat.save
#     redirect_to user_path(current_user)
#   else
#     redirect_to new_boat_path
#   end
# end

def edit
  @boat = Boat.find(params[:id])
end

def update
  @boat = Boat.find(params[:id])
  if @boat.update_attributes(boat_params)
    redirect_to boat_path(@boat)
  else
    render edit_boat_path(@boat) 
  end	
end

def destroy
 @user = User.find(params[:id])
 @boat= Boat.find(params[:id])
 if @user == current_user
   @boat.destroy
   flash[:alert] = "Shipment cancelled"
 else
   flash[:alert] = "You can't edit or cancel this shipment."
 end
 redirect_to user_path(@user)
end

private
def boat_params
  params.require(:boat).permit(:name, :location, :container, :avatar, :user_id)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		render layout: 'special'
	end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.all
  end

  def show
  	@job = Job.find(params[:id])
  end

  def new
    @boat = Boat.find(params[:boat_id])
  	@job = Job.new
  end

  def create
  	@boat= Boat.find(params[:boat_id])
  	@job = @boat.jobs.build(job_params)
  	@job.user = current_user
  	@job.save
  	redirect_to boat_path(@boat)
  end

private
	def job_params
		params.require(:job).permit(:name, :cost, :note, :origin, :destination)

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		

		@user = User.where(email: params[:email]).first
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			redirect_to login_path
		end	

	end

	def destroy
		session[:user_id] = nil
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
		if @user.save
			
			redirect_to user_path(@user)
		else
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
		@boats = Boat.new
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render edit_user_path(@user)
		end
	end	
 def destroy
 	@user = User.find(params[:id])
 	@user.delete
 	redirect_to users_path
 end

  private
	  def user_params
	  	params.require(:user).permit(:email, :password)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  # renders a given haml block inside a layout
  def inside_layout(layout)
        @view_flow.set(:layout, output_buffer)
    	output = render(:file => "layouts/#{layout}")
    	self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/boats/edit.html.erb
<!--Edit the boat's information on this index-->
<div class="new_item">
	<div id="edit_boat">
	<h2>Update the Boat</h2>
		<%=form_for @boat do |f|%>	
		<%=f.label :boat_name %>
		<%=f.text_field :name%>
		<br>
		<%=f.label :current_location%>
		<%=f.text_field :location%>
		<br>
		<%=f.label :Number_of_containers%>
		<%=f.text_field :container%> 
		<br>
		<br>
		<br>
		<%= f.file_field :avatar %>
	</div>
	<br>
		<!-- <div id="new_item_btn"> -->
		<%=f.submit "Update"%> 
		<!-- add code to Boat edit/update controller. User is redirected to the boat show path, and will see their changes -->
	<!-- 	</div> -->
		<%end%>
	</div>

app/views/boats/index.html.erb
<h2>All Boats</h2>
	<% @boats.each do |boat| %>
<%=link_to boat.name, boat_path(boat)%>
<br>
<br>
<%end%>

app/views/boats/new.html.erb
<div id="new_boat">
		<h4>Launch a new Boat</h4>
		<%=form_for @boat, html: { multipart: true } do |f|%>
		<%=f.label :boat_name %>
		<%=f.text_field :name%>
		<br>
		<%=f.label :current_location%>
		<%=f.text_field :location%>
		<br>
		<%=f.label :Number_of_containers%>
		<%=f.text_field :container%> 
		<br>
		<br>
		<br>
		<%= f.file_field :avatar %>
		<br>
	
		<%=f.submit "Launch this Ship"%>
		<%end%>
	</div>

app/views/boats/show.html.erb
<div class ="table">
	<div id ="table-one">
			<!-- <h1><%=@boat.name%></h1> -->
			<div id="table-one-nav">
				<h1><%=@boat.name%></h1>
				<ul>
					<li>Decomission</li>
					<li>Edit</li>
				</ul>	
			</div>
		<table>
			<thead>
				<body>
					<tr>
						<th>Location</th>
					</tr>
					<tr>
						<td><%= @boat.location %></td>
					</tr>
					<tr>
						<th>No. Containers</th>
					</tr>
					<tr>
						<td><%=@boat.container%></td>
					</tr>
					<tr>
						<th>Captain</th>
					</tr>
					<tr>
						<td><%=@boat.user.email%></td>
					</tr>
				</tbody>
			</thead>	
		</table>
	</div>
			<%= render 'jobs/show' %>
</div>
<%= image_tag @boat.avatar.url(:thumb) %>
	<br>
	<%=link_to 'Edit', edit_boat_path %>
	<br>
	<%=link_to 'Delete', method: :delete%>
	<br>

<%=link_to 'Add cargo to this boat', new_boat_job_path(@boat)%>

app/views/home/_index.html.erb
<!-- <div class="signup_btn">
	<p><%#= link_to 'Sign Up', new_user_path%><p>
</div>

<div class="body_image">
	<img src="/assets/octopus_green.jpg">
</div> -->



<!-- <div class="navbar">
	<ul>
		<li>x</li>
		<li>yy</li>
		<li>zzz</li>
	</ul>
</div> -->

<!-- <div class="footer">
		<ul>
			<li>a</li>
			<li>bb</li>
			<li>ccc</li>
		</ul>
	</div> -->

app/views/home/index.html.erb
<%#= render 'home/index' %>
	<div class="login_form">
		<%= form_tag login_path do%>
		<%= text_field_tag(:email, nil, placeholder: 'email') %>
		<%= password_field_tag(:password, nil, placeholder: 'password') %>
	</div>	
	
	<div class="login_btn">
		<%=submit_tag "Login" %>
		<br>
		<h4>OR</h4>
		<br>
	<%end%>
	</div>

app/views/jobs/_show.html.erb
<div id="table-two">
	<table>
		<thead>
		<tr>
			<th>Job Name</th>
			<th>Origin</th>
			<th>Destination</th>
			<th>Shipment Value</th>
			<th>Note</th>
		</tr>
	</thead>
	<tbody>
		<% @jobs.each do |job| %>
		<tr>
			<td><%=job.name%></td>
			<td><%=job.origin%></td>
			<td><%=job.destination%></td>
			<td><%=job.cost%></td>
			<td><%=job.note%></td>	
			<%end%>
	</tr>
	</tbody>
</table>
</div>


<%# @jobs.each do |job| %>
<!-- <tr> -->
	<!-- <td><%#=job.name%></td> -->
	<!-- <td><%#=job.cost%></td> -->



	

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>

app/views/jobs/new.html.erb
<h1>Jobs</h1>
<p>Tell us about your shipment:/<p>
	<!-- Where are you shipping from?
	Where are you shipping to?
	Name this job
	Specify the cost of the cargo (<$1k)
	Optional: Add a note ("handle with care, do not stack, etc") -->
	

<h2>Add cargo to this Boat</h2>
	<%=form_for [@boat, @job] do |f|%>
	<%=f.label :job_name %>
	<%=f.text_field :name%>
	<br>
	<%=f.label :Ship_From%>
	<%=f.text_field :origin%>
	<%=f.label :Ship_To%>
	<%=f.text_field :destination%>
	<%=f.label :Value_of_cargo%> 
	<%=f.text_field :cost%>
	<%=f.label :description%>
	<%=f.text_field :note%>
	<br>
	<br>
	<%=f.submit "Create Job"%>
	<%end%>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AhoyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>

<body>
	<!-- <body background="/assets/waves.jpg"> -->
	<% if flash[:alert] %>
	    <div class="flash notice">
	      <%= flash[:alert] %>
	    </div>
    <% end %>
    	<div class="nav_bar">
		<ul>
			<li>
				<div id="logo"><h2>Ahoy</h2></div>
			</li>
			<li>
				<!-- <h4><%#= @user.email%> is logged in</h4> -->
			</li>
		</ul>
	</div>
	<%=yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AhoyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>

	<% if flash[:alert] %>
	    <div class="flash_notice">
	      <%= flash[:alert] %>
	    </div>
    <% end %>

</div>

<h1>this is my nav</h1>
<%=yield %>
<h1>this is my footer</h1>
	
</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AhoyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="page-wrap">
	<% if flash[:alert] %>
	    <div class="flash notice">
	      <%= flash[:alert] %>
	    </div>
    <% end %>
    	

		<div id="spec_logo">
			<h1>Ahoy!</h1>
		</div>

		<div class="body_image">
			<img src="/assets/octopus_green.jpg">
		</div>

		<%=yield %>
		<br>
		<div class="signup_btn">
	    	<p><%= link_to 'Sign Up', new_user_path%><p>
		</div> 
		
	</div>
</body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<h2>Create new user</h2>
<div class="form">
	<%= form_for(@user) do |f| %>
	<%=f.label :email %>
	<%=f.text_field :email%>
	<br>
	<br><%=f.label :password%>
	<%=f.password_field :password%>
	<br>
	<br>
	<%=f.submit "Create Account"%>
<%end%>
</div>

app/views/users/show.html.erb
<div class="wrapper">
	<%= link_to 'Launch a New Boat', new_boat_path%>
	<!-- <div id="new_boat">
		<h4>Launch a new Boat</h4>
		<%#=form_for @boats, url: boats_path, html: { multipart: true } do |f|%>
		<%#=f.label :boat_name %>
		<%#=f.text_field :name%>
		<br>
		<%#=f.label :current_location%>
		<%#=f.text_field :location%>
		<br>
		<%#=f.label :Number_of_containers%>
		<%#=f.text_field :container%> 
		<br>
		<br>
		<br>
		<%#= f.file_field :avatar %>
		<br>
	
		<%#=f.submit "Launch this Ship"%>
		<%#end%>
	</div> -->
<!-- </div> -->

	<div id="profile">
		<h4>Your Shipments</h4>
		<% @user.boats.each do |b| %>
		<li><%= link_to b.name, boat_path(b)%></li>
		<br>
		<%end%>
		<h5><%=link_to 'See All Shipments', boats_path%></h5>
	</div>
</div>